import antfu from '@antfu/eslint-config'
import nextPlugin from '@next/eslint-plugin-next'
import jsxA11y from 'eslint-plugin-jsx-a11y'

export default antfu(
  {
    formatters: true,
    react: true,
    typescript: true,
  },
  jsxA11y.flatConfigs.recommended,
  {
    plugins: {
      '@next/next': nextPlugin,
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
    },
  },
  {
    rules: {
      'no-console': 'off',
      'unicorn/no-instanceof-builtins': 'off',
      'unicorn/prefer-number-properties': 'off',
      'unicorn/number-literal-case': 'off',
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/no-explicit-any': 'off',
      'react/no-array-index-key': 'off',
      'react/no-context-provider': 'off',
      'react-refresh/only-export-components': 'off',
      'react-hooks-extra/no-direct-set-state-in-use-effect': 'off',
      'jsx-a11y/no-autofocus': 'off',
      'style/no-trailing-spaces': 'off',
      'style/comma-dangle': 'off',
      'style/brace-style': 'off',
      'style/eol-last': 'off',
      'style/arrow-parens': 'off',
      'style/multiline-ternary': 'off',
      'style/space-infix-ops': 'off',
      'perfectionist/sort-imports': 'off',
      'perfectionist/sort-named-imports': 'off',
      'unused-imports/no-unused-imports': 'warn',
      'unused-imports/no-unused-vars': 'warn',
      'node/prefer-global/process': 'off',
      'node/prefer-global/buffer': 'off',
      'ts/no-require-imports': 'off',
      'prefer-const': 'warn',
      'regexp/no-super-linear-backtracking': 'off',
      'style/operator-linebreak': 'off',
      'style/indent-binary-ops': 'off',
      'style/indent': 'off',
      'style/jsx-closing-bracket-location': 'off',
      'style/jsx-one-expression-per-line': 'off',
      'style/member-delimiter-style': 'off',
      'unicorn/prefer-node-protocol': 'off',
      'unicorn/new-for-builtins': 'off',
      'prefer-template': 'off',
      'import/consistent-type-specifier-style': 'off',
      'react/no-forward-ref': 'off',
      'antfu/top-level-function': 'off',
      'antfu/if-newline': 'off',
      'antfu/consistent-chaining': 'off',
      'perfectionist/sort-named-exports': 'off',
      'jsx-a11y/label-has-associated-control': 'off',
      'prefer-exponentiation-operator': 'off',
      'style/lines-between-class-members': 'off',
    },
  },
)
